version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: judge
      POSTGRES_USER: admin
      
  judge:
    container_name: judge    
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    image: judge-pcs3616
    restart: always
    depends_on:
      - db
    volumes:      
      - .docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80
    environment:
      APP_BASE_URL: ${APP_BASE_URL}
      APP_TIMEZONE: ${APP_TIMEZONE}
      APP_TESTER_PATH: ${APP_TESTER_PATH}
      APP_ASSIGNMENTS_ROOT: ${APP_ASSIGNMENTS_ROOT}
      APP_SMTP_USER: ${APP_SMTP_USER}
      APP_SMPT_PASS: ${APP_SMPT_PASS}
      APP_SMTP_HOST: ${APP_SMTP_HOST}
      APP_SMTP_PORT: ${APP_SMTP_PORT}
