version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: judge
      POSTGRES_USER: admin      
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  judge:
    container_name: judge
    build: './.docker'
    image: judge-pcs3616
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app 
      - .docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 80:80
volumes:
    postgresql-data: